<?php
$this->title = "Uživatelé";
$this->headTitle($this->title);
?> 

<section id="container">
    <div class="row">
        <div id="sidebar" class="col-md-2">
            <div class="user">
                <div class="user-img">
                    <i class="fa fa-user fa-5x"></i>
                </div>                
                <div class="user-info">
                    <?php
                    $auth = Zend_Auth::getInstance();
                    if ($auth->hasIdentity()) {
                        $user = $auth->getIdentity();
                        $accessLevel = $this->escape($user->AccessLevel);
                        $id = $this->escape($user->id);
                        echo "<span>$accessLevel</span>";
                        ?>
                    <br>
                        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'show', 'id' => $id)); ?>">Můj profil</i></a>
                        <?php
                    }
                    ?>
<!--                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add')) ?>">Můj profil</a>-->

                </div>
            </div>

            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="  search-query form-control" placeholder="Vyhledat" />
                    <span class="input-group-btn">
                        <button class="btn btn-danger" type="button">
                            <span class=" glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="sidebar-nav">
                <div class="navbar" role="navigation">                    
                    <div class="navbar-collapse collapse sidebar-navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'list-of-users')) ?>"><i class="fa fa-list"></i> Seznam uživatelů</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'RulesBlack', 'action' => 'list-of-rules')) ?>"><i class="fa fa-cog"></i> Správa pravidel</a></li>
                            <li><a href="#">Menu Item 3</a></li>
                            <li><a href="#">Menu Item 4</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>                
            </div>

        </div>
        <div id="content" class="col-md-10">
            <h1>Výpis všech uživatelů</h1>
            <div class="horizontal-menu">                
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'add')) ?>"><i class="fa fa-user-plus fa-lg"></i>Nový uživatel</a></li>                    
                </ul>
            </div>
            <table class="table table-hover">

                <thead>
                    <tr>
                        <th>Datum přidání</th>
                        <th>Přidal</th>
                        <th>Úroveň přístupu</th>
                        <th>Email</th>
                        <th>Číslo smlouvy</th>
                        <th>Heslo</th>
                        <th>Komentář</th>
                    </tr>
                </thead>
                <?php foreach ($this->user as $key => $value) { ?> 
                    <tbody> 
                        <tr class="active">
                            <?php
                            echo "<td>$value->DateOfSign </td> "
                            . "<td>$value->Creator </td> "
                            . "<td>$value->AccessLevel </td> "
                            . "<td>$value->Email</td> "
                            . "<td>$value->ContractNumber</td> "
                            . "<td>$value->Password</td> "
                            . "<td>$value->Comment</td>"
                            ?>
                            <td class="delete-btn"><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'delete', 'id' => $value->id)); ?>"><i class="fa fa-trash"></i></a></td>                            
                            <td class="edit-btn"><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'edit', 'id' => $value->id)); ?>"><i class="fa fa-pencil"></i></a></td>
                            <td class="edit-btn"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'show', 'id' => $value->id)); ?>"><i class="fa fa-pencil"></i></a></td>
                                <?php } ?> 
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</section>




