<?php
$this->title = "Přihlášení";
$this->headTitle($this->title);
?> 

<section id="slider">
    <div class="row">
        <div class="col-md-8">
            <h1>Bezpečná e-mailová komunikace</h1>
            <h4>Virusfree chrání vaši e-mailovou komunikaci před viry, spamem a útoky z internetu. Kombinace jednoduchosti a mimořádné spolehlivosti z něj činí nejefektivnější produkt svého druhu. Na Virusfree spoléhají významné firmy i veřejné instituce. Spolehněte se také!</h4>
            <a class="btn btn-5 btn-5a icon-start-now homepage-btn" href="#"><span>Vyzkoušet</span></a>
        </div>
        <div class="col-md-4">
        <div class="login-form-section">
            <form>
                <div class="section-title">
                    <h3>Příhlásit se</h3>
                </div>
                <div class="textbox-wrap">
                    <div class="input-group">
                        <span class="input-group-addon "><i class="fa fa-user"></i></span>
                        <input required="required" class="form-control" placeholder="E-mail" type="text">
                    </div>
                </div>
                <div class="textbox-wrap">
                    <div class="input-group">
                        <span class="input-group-addon "><i class="fa fa-lock"></i></span>
                        <input required="required" class="form-control " placeholder="Heslo" type="password">
                    </div>
                </div>
                <div class="login-form-action clearfix">
                    <a><i class="fa fa-unlock"></i> Zapomněli jste heslo?</a>
                    <button type="submit" class="btn btn-success pull-right green-btn">Přihlásit<i class="icon-chevron-right"></i></button>
                </div>
            </form>
        </div>   
    </div>
    </div>
    
    
</section>
<section id="about">

</section>

