<?php
$this->title = "Smazání";
$this->headTitle($this->title);
?>
<p>Opravdu chcete smazat pravidlo 
    <?php echo $this->escape($this->rule['Name']);?>    
</p> 

<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div> 
        <input type="hidden" name="id" value="<?php echo $this->rule['id']; ?>" /> 
        <input type="submit" name="del" value="Ano" /> 
        <input type="submit" name="del" value="Ne" />
    </div>
</form>
