<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('NOSPAM');
echo $this->doctype();
echo $this->headLink()
        ->appendStylesheet($this->baseUrl() . '/css/font-awesome.css')
        ->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->baseUrl() . '/css/site.css') //díky prepend budou další styly renderovány až po stylopisu site.css
        ->appendStylesheet($this->baseUrl() . '/css/content.css');
echo $this->HeadScript()
        ->appendFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript')
        ->appendFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript');
?> 
<html>
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        ?>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"><i class="fa fa-hand-paper-o"></i><span>NO</span>spam</a>

                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">Link</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add')) ?>">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">One more separated link</a></li>                                                              
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <?php
                            $auth = Zend_Auth::getInstance();
                            if ($auth->hasIdentity()) {
                                $user = $auth->getIdentity();
                                ?>                     
                                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout')) ?>"><?php echo$this->escape($user->Email) ?></a></li>
                                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout')) ?>">Odhlasit</a></li>
                            <?php } ?>
                        </ul>
                    </div><!-- /.container-fluid -->

            </nav>            
        </header>

        <?php echo $this->layout()->content; ?>
        <footer>
            Footer
        </footer>

        <?php
        echo $this->inlineScript()
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
                ->appendFile($this->baseUrl() . '/js/jquery-effects.js');
        ?>
    </body>
</html>

