<?php
$this->title = "Uživatelé";
$this->headTitle($this->title);
?> 

<section id="container">
    <div class="row">
        <div id="sidebar" class="col-md-2">
            <div class="user">
                <div class="user-img">
                    <i class="fa fa-user fa-5x"></i>
                </div>                
                <div class="user-info">
                    <?php
                    $auth = Zend_Auth::getInstance();
                    if ($auth->hasIdentity()) {
                        $user = $auth->getIdentity();
                        $accessLevel = $this->escape($user->AccessLevel);
                        $FirstName = $this->escape($user->FirstName);
                        $lastName = $this->escape($user->LastName);
                        echo "<span>$accessLevel</span>" . "<h5>$FirstName $lastName </h5>" ;

                        // echo $this->escape($user->FirstName) . ' ' . $this->escape($user->LastName);
                    }
                    ?>
<!--                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add')) ?>">Můj profil</a>-->

                </div>
            </div>

            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="  search-query form-control" placeholder="Vyhledat" />
                    <span class="input-group-btn">
                        <button class="btn btn-danger" type="button">
                            <span class=" glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="sidebar-nav">
                <div class="navbar" role="navigation">                    
                    <div class="navbar-collapse collapse sidebar-navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'list-of-users')) ?>"><i class="fa fa-list"></i> Seznam uživatelů</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'list-of-users')) ?>"><i class="fa fa-cog"></i> Správa pravidel</a></li>
                            <li><a href="#">Menu Item 3</a></li>
                            <li><a href="#">Menu Item 4</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>                
            </div>

        </div>
        <div id="content" class="col-md-10">
            <h1>Výpis všech uživatelů</h1>
            <div class="horizontal-menu">                
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add')) ?>"><i class="fa fa-user-plus fa-lg"></i>Nový uživatel</a></li>                    
                </ul>
            </div>
            <table class="table">

                <thead>
                    <tr>
                        <th>Úroveň přístupu</th>
                        <th>Email</th>
                        <th>Jméno</th>
                        <th>Příjmení</th>
                        <th>Telefonní číslo</th>
                        <th>Heslo</th>
                        <th>Komentář</th>
                    </tr>
                </thead>
                <?php foreach ($this->user as $key => $value) { ?> 
                    <tbody> 
                        <tr class="active">
                            <?php
                            echo "<td>$value->AccessLevel </td> "
                            . "<td>$value->Email</td> "
                            . "<td>$value->FirstName</td> "
                            . "<td>$value->LastName</td> "
                            . "<td>$value->TelNumber</td> "
                            . "<td>$value->Password</td>"
                            . "<td>$value->Comment</td>"
                            ?>
                            <td>

                                <a href="<?php
                                echo $this->url(array('controller' => 'user',
                                    'action' => 'delete', 'id' => $value->id));
                                ?>">Delete</a>
                                <a href="<?php
                                echo $this->url(array('controller' => 'user',
                                    'action' => 'edit', 'id' => $value->id));
                                ?>">Editovat</a>
                            </td>
                        <?php } ?> 
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</section>




