<?php
$this->title = "Profil";
$this->headTitle($this->title);
?> 

<section id="container">
    <div class="row">
        <div id="sidebar" class="col-md-2">
            <div class="user">
                <div class="user-img">
                    <i class="fa fa-user fa-5x"></i>
                </div>                
                <div class="user-info">
                    <?php
                    $auth = Zend_Auth::getInstance();
                    if ($auth->hasIdentity()) {
                        $user = $auth->getIdentity();
                        $accessLevel = $this->escape($user->AccessLevel);
                        $id = $this->escape($user->id);
                        echo "<span>$accessLevel</span>";
                        ?>
                        <br>
                        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'show', 'id' => $id)); ?>">Můj profil</i></a>
                        <?php
                    }
                    ?>
<!--                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add')) ?>">Můj profil</a>-->

                </div>
            </div>

            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="  search-query form-control" placeholder="Vyhledat" />
                    <span class="input-group-btn">
                        <button class="btn btn-danger" type="button">
                            <span class=" glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="sidebar-nav">
                <div class="navbar" role="navigation">                    
                    <div class="navbar-collapse collapse sidebar-navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'list-of-users')) ?>"><i class="fa fa-list"></i> Seznam uživatelů</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'RulesBlack', 'action' => 'list-of-rules')) ?>"><i class="fa fa-cog"></i> Správa pravidel</a></li>
                            <li><a href="#">Menu Item 3</a></li>
                            <li><a href="#">Menu Item 4</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>                
            </div>

        </div>
        <div id="content" class="col-md-10">
            <h1><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'list-of-users')) ?>"><i class="fa fa-arrow-circle-o-left"></i></a> Profil</h1><hr>          
            
            <?php foreach ($this->userInfo['user_info'] as $value) { ?>
                 <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'edit', 'id' => $value ['id'])); ?>"><i class="fa fa-pencil"></i></a>
                <div class="message-info">
                    <h3><i class="fa fa-user" aria-hidden="true"></i> Obecné</h3>
                    <div class="table-responsive">
                        <table class="table table-sm">
                            <tr class="active">
                                <th class="col-md-2" scope="row">Jméno:</th>                            
                                <td class="col-md-10"><?php print $value ['FirstName']; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">Příjmení:</th>                           
                                <td><?php print $value ['LastName']; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">Telefonní číslo:</th>                            
                                <td><?php print $value ['TelNumber']; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">Komentář:</th>                           
                                <td><?php print $value ['Comment']; ?> </td>                
                            </tr>
                            <?php
                        }

                        if ($auth->hasIdentity()) {
                            $user = $auth->getIdentity();
                            $accessLevel = $this->escape($user->AccessLevel);
                            $email = $this->escape($user->Email);
                            $contractNumber = $this->escape($user->ContractNumber);
                            $dateOfSign = $this->escape($user->DateOfSign);
                            $creater = $this->escape($user->Creator);
                            ?>
                            <tr>
                                <th scope="row">*Úroveň přístupu:</th>                           
                                <td><?php print $accessLevel; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">*Email:</th>                           
                                <td><?php print $email; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">*Číslo smlouvy:</th>                            
                                <td><?php print $contractNumber; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">*Registrace:</th>                             
                                <td><?php print $dateOfSign; ?> </td>                
                            </tr>
                            <tr>
                                <th scope="row">*Registroval:</th>                             
                                <td><?php print $creater; ?> </td>                
                            </tr>                     
                            <?php
                        }
                        ?>
                            
                    </table>
                </div>
                    <p style="color: #999999">Poznámka: Údaje označené hvězdičkou může změnit pouze administrátor</p>
                </div>
                <?php foreach ($this->address['address'] as $value) { ?>
                    <a href="<?php echo $this->url(array('controller' => 'address', 'action' => 'edit', 'id' => $value ['id'])); ?>"><i class="fa fa-pencil"></i></a>
                    <div class="message-info">
                        <h3><i class="fa fa-map-marker" aria-hidden="true"></i> Adresa</h3>
                        <div class="table-responsive">
                            <table class="table table-sm">                                
                                <tr>
                                    <th class="col-md-2" scope="row">Město:</th>                           
                                    <td class="col-md-10"> <?php print $value ['City']; ?> </td>                
                                </tr>
                                <tr>
                                    <th scope="row">Ulice:</th>                           
                                    <td><?php print $value ['Street']; ?> </td>                
                                </tr>
                                <tr>
                                    <th scope="row">PSČ:</th>                           
                                    <td><?php print $value ['ZipCode']; ?> </td>                
                                </tr>
                                <tr>
                                    <th scope="row">Stát:</th>                           
                                    <td><?php print $value ['State']; ?> </td>                
                                </tr>                   
                            <?php }
                            ?>
                    </div> 

                    </table>
                </div>
            </div>

        </div>
    </div>
</section>



